version: '3'

services:

    postgres:
      container_name: postgres_container
      image: postgres
      environment:
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123qweasd}
        POSTGRES_DB: ${POSTGRES_DB:-fileserverbd}
        PGDATA: /data/postgres
      volumes:
         - ./data.sql:/docker-entrypoint-initdb.d/init.sql
         - postgres:/data/postgres
      ports:
        - "6543:5432"
      networks:
        - postgres
      restart: unless-stopped
    auth-service:
      image: auth:1.0
      networks:
        - postgres
        - httpnetwork
        - ftpnetwork
      ports: 
        - "5001:5001"
    httpservice:
      image: http:1.0
      networks: 
        - httpnetwork
      ports: 
        - "8001:8001"
    ftpservice:
      image: ftp:1.0
      networks:
        - ftpnetwork
      ports:
        - "21:21"
       
networks: 
    postgres:
      driver: bridge
    httpnetwork:
    ftpnetwork:
volumes:
  postgres:
  
    
