version: '3'

services:

    postgres:
      container_name: postgres_container
      image: postgres
      environment:
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123qweasd}
        POSTGRES_DB: ${POSTGRES_DB:-fileserverbd}
        PGDATA: /data/postgres
      volumes:
         - ./init:/docker-entrypoint-initdb.d/
         - postgres:/data/postgres
      ports:
        - "6543:5432"
      networks:
        - postgres
      restart: unless-stopped
    auth-service:
      container_name: auth_container
      image: auth:1.0
      networks:
        - postgres
        - httpnetwork
        - ftpnetwork
      ports: 
        - "5001:5001"
    httpservice:
      container_name: http_container
      image: http:1.0
      networks: 
        - httpnetwork
      ports: 
        - "8001:8001"
      volumes:
        - servervol:/usr/src/http
    ftpservice:
      container_name: ftp_container
      image: ftp:1.0
      networks:
        - ftpnetwork
      ports:
        - "21:21"
      volumes:
        - servervol:/usr/src/ftp       
networks: 
    postgres:
    httpnetwork:
    ftpnetwork:
volumes:
  postgres:
  servervol:
    
